START RequestId: 732c8dfe-619f-4399-8ac2-6994ca1227ce Version: $LATEST
2024-02-05T08:08:53.274Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"handleCallback is not defined","stack":["ReferenceError: handleCallback is not defined","    at Object.<anonymous> (/var/task/src/shared/utils.js:132:5)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)","    at Module.load (node:internal/modules/cjs/loader:1197:32)","    at Module._load (node:internal/modules/cjs/loader:1013:12)","    at Module.require (node:internal/modules/cjs/loader:1225:19)","    at require (node:internal/modules/helpers:177:18)","    at Object.<anonymous> (/var/task/src/handlers/Xero/getXero.js:8:15)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)"]}
05 Feb 2024 08:08:53,297 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
05 Feb 2024 08:08:53,301 [ERROR] (rapid) Invoke failed error=Runtime exited with error: exit status 129 InvokeID=10aba386-f65a-402f-855b-bd709066f725
05 Feb 2024 08:08:53,301 [ERROR] (rapid) Invoke DONE failed: Sandbox.Failure

START RequestId: 75646cf0-c1c0-4428-ac26-78fcc30f2a65 Version: $LATEST
2024-02-05T08:09:10.626Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"handleCallback is not defined","stack":["ReferenceError: handleCallback is not defined","    at Object.<anonymous> (/var/task/src/shared/utils.js:132:5)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)","    at Module.load (node:internal/modules/cjs/loader:1197:32)","    at Module._load (node:internal/modules/cjs/loader:1013:12)","    at Module.require (node:internal/modules/cjs/loader:1225:19)","    at require (node:internal/modules/helpers:177:18)","    at Object.<anonymous> (/var/task/src/handlers/Xero/getXero.js:8:15)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)"]}
05 Feb 2024 08:09:10,649 [ERROR] (rapid) Invoke failed error=Runtime exited with error: exit status 129 InvokeID=9a23d834-582a-4798-87ad-03e2eb0e1e17
05 Feb 2024 08:09:10,649 [ERROR] (rapid) Invoke DONE failed: Runtime.ExitError

START RequestId: 8a4de0ce-c2fe-4ed0-a16b-189037764bc9 Version: $LATEST
2024-02-05T08:11:17.827Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"handleCallback is not defined","stack":["ReferenceError: handleCallback is not defined","    at Object.<anonymous> (/var/task/src/shared/utils.js:132:5)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)","    at Module.load (node:internal/modules/cjs/loader:1197:32)","    at Module._load (node:internal/modules/cjs/loader:1013:12)","    at Module.require (node:internal/modules/cjs/loader:1225:19)","    at require (node:internal/modules/helpers:177:18)","    at Object.<anonymous> (/var/task/src/handlers/Xero/getXero.js:8:15)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)"]}
05 Feb 2024 08:11:17,848 [ERROR] (rapid) Invoke failed InvokeID=3af357e9-3c40-4793-87e0-d7c837391248 error=Runtime exited with error: exit status 129
05 Feb 2024 08:11:17,848 [ERROR] (rapid) Invoke DONE failed: Runtime.ExitError

START RequestId: 704bbef1-f390-4068-ad9e-08af27046171 Version: $LATEST
2024-02-05T08:22:17.529Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"handleCallback is not defined","stack":["ReferenceError: handleCallback is not defined","    at Object.<anonymous> (/var/task/src/shared/utils.js:132:5)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)","    at Module.load (node:internal/modules/cjs/loader:1197:32)","    at Module._load (node:internal/modules/cjs/loader:1013:12)","    at Module.require (node:internal/modules/cjs/loader:1225:19)","    at require (node:internal/modules/helpers:177:18)","    at Object.<anonymous> (/var/task/src/handlers/Xero/getXero.js:8:15)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)"]}
05 Feb 2024 08:22:17,552 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited with error: exit status 129
05 Feb 2024 08:22:17,552 [ERROR] (rapid) Invoke failed error=Runtime exited with error: exit status 129 InvokeID=9dabc9e8-d8d2-42f7-a565-051fde7a8587
05 Feb 2024 08:22:17,552 [ERROR] (rapid) Invoke DONE failed: Sandbox.Failure

START RequestId: 3caefa59-b0dd-4676-8f93-a4fc81b0621b Version: $LATEST
2024-02-05T08:29:15.418Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"handleCallback is not defined","stack":["ReferenceError: handleCallback is not defined","    at Object.<anonymous> (/var/task/src/shared/utils.js:132:5)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)","    at Module.load (node:internal/modules/cjs/loader:1197:32)","    at Module._load (node:internal/modules/cjs/loader:1013:12)","    at Module.require (node:internal/modules/cjs/loader:1225:19)","    at require (node:internal/modules/helpers:177:18)","    at Object.<anonymous> (/var/task/src/handlers/Xero/getXero.js:8:15)","    at Module._compile (node:internal/modules/cjs/loader:1356:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)"]}
05 Feb 2024 08:29:15,439 [ERROR] (rapid) Invoke failed InvokeID=3b5c9cb2-68d1-473c-82a1-bec39f3d794b error=Runtime exited with error: exit status 129
05 Feb 2024 08:29:15,439 [ERROR] (rapid) Invoke DONE failed: Runtime.ExitError

